<a href="https://colab.research.google.com/github/naeema3445/Online-Courses-Learning/blob/master/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
X = np.random.rand(3,3)
print(X)

[[0.71716802 0.26107724 0.42535891]
 [0.97716159 0.79295921 0.67584725]
 [0.72935643 0.5476387  0.90184004]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np
x = np.arange(3, 19).reshape(4,4)
print(x)
y = np.arange(2,18).reshape(4,4)
print(y)
x = np.arange(3,19).reshape(2,8)
y = np.arange(2,18).reshape(2,8)
u = np.vstack((x,y))
print(u)
z = np.hstack((x,y))
print(z)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]]
[[ 3  4  5  6  7  8  9 10  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 10 11 12 13 14 15 16 17]]
